name: "release"

on:
  workflow_dispatch:

jobs:
  create_release:
    runs-on: ubuntu-latest
    name: Create release
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: create release
        run: |
          npm install @semantic-release/gitlab @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/git @semantic-release/changelog conventional-changelog-conventionalcommits
          npx semantic-release
    

   