plugins:
  - "@semantic-release/github"
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      releaseRules:
      - type: docs
        scope: README
        release: patch
      - type: refactor
        release: patch
      - type: style
        release: patch
      parserOpts:
        noteKeywords:
        - BREAKING CHANGE
        - BREAKING CHANGES
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
  - - "@semantic-release/git"
  - assets:
    - CHANGELOG.md

branches:
  - "main"
