plugins:
  - "@semantic-release/github"
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      parserOpts:
        noteKeywords:
        - BREAKING CHANGE
        - BREAKING CHANGES
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
  - - "@semantic-release/git"
  - assets:
    - CHANGELOG.md

branches:
  - "main"
